const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="mawaeedi_v20", OLDKEY="mawaeedi_v14", pad=n=>String(n).padStart(2,"0");
const isoToday=()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||JSON.parse(localStorage.getItem(OLDKEY)||'{"profile":{},"reminders":[],"documents":[],"settings":{}}');
state.profile??={}; state.reminders??=[]; state.documents??=[]; state.settings??={};
let calendarDate=new Date(), reminderFilter="all", docFilter="all";

const holidays=[
["2026-11-01","ذكرى اندلاع الثورة التحريرية","🇩🇿","عطلة رسمية",false],["2027-01-01","رأس السنة الميلادية","🎉","عطلة رسمية",false],["2027-01-12","يناير / رأس السنة الأمازيغية","ⵣ","عطلة رسمية",false],["2027-02-08","بداية رمضان","🌙","مناسبة دينية",true],["2027-02-22","يوم الأخوة والوحدة","🇩🇿","مناسبة",false],["2027-03-10","عيد الفطر","🌙","عطلة دينية",true],["2027-03-11","عطلة عيد الفطر","🌙","عطلة دينية",true],["2027-03-12","عطلة عيد الفطر","🌙","عطلة دينية",true],["2027-05-01","عيد العمال","🛠️","عطلة رسمية",false],["2027-05-17","عيد الأضحى","🐑","عطلة دينية",true],["2027-05-18","عطلة عيد الأضحى","🐑","عطلة دينية",true],["2027-06-06","رأس السنة الهجرية / محرم","🕌","عطلة دينية",true],["2027-06-15","عاشوراء","🕌","عطلة دينية",true],["2027-07-05","عيد الاستقلال والشباب","🇩🇿","عطلة رسمية",false],["2027-08-15","المولد النبوي الشريف","🕌","عطلة دينية",true],["2027-11-01","ذكرى اندلاع الثورة التحريرية","🇩🇿","عطلة رسمية",false]];

function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmtDate(s,o={day:"numeric",month:"long",year:"numeric"}){return s?new Intl.DateTimeFormat("ar-DZ",o).format(new Date(s+"T12:00:00")):""}
function diffDays(target){const a=new Date();a.setHours(0,0,0,0);return Math.ceil((new Date(target+"T00:00:00")-a)/86400000)}
function countdown(t){const d=diffDays(t);return d<0?"انتهى":d===0?"اليوم":d===1?"غدًا":`باقي ${d} يوم`}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function addDate(s,n){const d=new Date(s+"T12:00:00");d.setDate(d.getDate()+n);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function repeatDates(start,repeat,end){if(repeat==="none")return[start];let out=[],d=new Date(start+"T12:00:00"),limit=end?new Date(end+"T12:00:00"):new Date(d);if(!end)limit.setFullYear(limit.getFullYear()+1);for(let i=0;i<60&&d<=limit;i++){out.push(`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`);if(repeat==="daily")d.setDate(d.getDate()+1);else if(repeat==="weekly")d.setDate(d.getDate()+7);else if(repeat==="monthly")d.setMonth(d.getMonth()+1);else d.setFullYear(d.getFullYear()+1)}return out}
function showPage(id){$$(".page").forEach(p=>p.classList.toggle("active",p.id===id));$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.go===id));scrollTo(0,0);if(id==="calendar")renderCalendar();if(id==="reminders")renderReminders();if(id==="documents")renderDocuments();if(id==="holidays")renderHolidays();if(id==="home")renderHome()}
document.addEventListener("click",e=>{const b=e.target.closest("[data-go]");if(b)showPage(b.dataset.go)});
function renderClock(){const n=new Date();$("#clock").textContent=n.toLocaleTimeString("ar-DZ",{hour:"2-digit",minute:"2-digit",second:"2-digit"});$("#todayText").textContent=n.toLocaleDateString("ar-DZ",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function calculateAge(b){if(!b)return null;const x=new Date(b+"T00:00:00"),n=new Date();let y=n.getFullYear()-x.getFullYear(),m=n.getMonth()-x.getMonth(),d=n.getDate()-x.getDate();if(d<0){m--;d+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}let next=new Date(n.getFullYear(),x.getMonth(),x.getDate());if(next<=n)next.setFullYear(n.getFullYear()+1);return{y,m,d,next:`${next.getFullYear()}-${pad(next.getMonth()+1)}-${pad(next.getDate())}`}}
function workInfo(){const p=state.profile, wd=Number(p.workDays)||0,od=Number(p.offDays)||0,start=p.cycleStart;if(!wd||!start||wd+od<=0)return null;const cycle=wd+od,days=Math.floor((new Date(isoToday()+"T12:00:00")-new Date(start+"T12:00:00"))/86400000),pos=((days%cycle)+cycle)%cycle,working=pos<wd;return{working,pos,remaining:working?wd-pos:cycle-pos,wd,od}}
function nextHoliday(){return holidays.filter(h=>h[0]>=isoToday()).sort((a,b)=>a[0].localeCompare(b[0]))[0]}
function dueItems(){return state.documents.filter(x=>diffDays(x.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))}
function remIcon(t){return{appointment:"📌",document:"📄",car:"🚗",money:"💰",birthday:"🎂",other:"📝"}[t]||"📝"}
function remCard(x){return `<div class="list-item ${x.done?"done":""}"><div class="item-icon">${remIcon(x.type)}</div><div class="item-main"><strong>${escapeHtml(x.title)}</strong><span>${fmtDate(x.date)} • ${x.time||""}${x.repeat&&x.repeat!=="none"?" • 🔁 "+repeatLabel(x.repeat):""}</span></div><div class="item-side">${countdown(x.date)}<div><button class="mini" onclick="toggleDone('${x.id}')">${x.done?"↩":"✓"}</button><button class="mini danger-mini" onclick="deleteReminder('${x.id}')">×</button></div></div></div>`}
function repeatLabel(r){return{daily:"يومي",weekly:"أسبوعي",monthly:"شهري",yearly:"سنوي"}[r]||""}
function renderHome(){
 renderClock();const a=calculateAge(state.profile.birthDate);$("#ageValue").textContent=a?`${a.y} سنة`:"أدخل تاريخ ميلادك";$("#ageDetails").textContent=a?`${a.m} شهر و ${a.d} يوم • عيد الميلاد القادم ${fmtDate(a.next)}`:"من بياناتي أضف تاريخ الميلاد";
 const wi=workInfo();$("#workStatus").textContent=wi?(wi.working?"🟢 أنت في أيام العمل":"🔵 أنت في أيام الراحة"):"اضبط نظام العمل";$("#workDetails").textContent=wi?`متبقي ${wi.remaining} يوم • دورة ${wi.wd}/${wi.od}`:"مثال: 20 عمل / 20 راحة + تاريخ البداية";
 const sal=Number(state.profile.monthlySalary)||0;$("#salaryValue").textContent=sal?`${sal.toLocaleString("ar-DZ")} دج`:"—";$("#salaryDetails").textContent=sal?`اليوم ${state.profile.payDay||30} من الشهر`:"أضف راتبك من بياناتي";
 const arr=state.reminders.filter(x=>!x.done&&x.date>=isoToday()).sort((a,b)=>(a.date+"T"+(a.time||"")).localeCompare(b.date+"T"+(b.time||"")));const nr=arr[0];$("#nextReminder").textContent=nr?countdown(nr.date):"لا يوجد";$("#nextReminderDetails").textContent=nr?`${escapeHtml(nr.title)} • ${nr.time||""}`:"أضف موعدك الأول";
 $("#upcomingCount").textContent=arr.length;$("#dueCount").textContent=dueItems().filter(x=>diffDays(x.date)<=30).length;$("#daysWorked").textContent=wi&&wi.working?wi.wd:0;$("#daysOff").textContent=wi&&!wi.working?wi.od:0;
 $("#upcomingList").innerHTML=arr.slice(0,4).map(remCard).join("")||`<div class="empty">ما عندك حتى موعد قريب. أضف أول موعد 👇</div>`;
 const docs=dueItems().slice(0,4);$("#dueList").innerHTML=docs.map(docCard).join("")||`<div class="empty">لا توجد وثائق أو استحقاقات مضافة.</div>`;
 const h=nextHoliday();$("#holidayCard").innerHTML=h?`<div class="holiday-line"><div class="holiday-icon">${h[2]}</div><div><strong>${h[1]}</strong><div class="muted">${fmtDate(h[0])} • ${countdown(h[0])}${h[4]?" • تاريخ تقريبي":""}</div></div></div>`:"لا توجد بيانات قادمة";
}
window.toggleDone=id=>{const x=state.reminders.find(r=>r.id===id);if(x){x.done=!x.done;save();renderHome();renderReminders()}}
window.deleteReminder=id=>{if(confirm("حذف هذا الموعد؟")){state.reminders=state.reminders.filter(x=>x.id!==id);save();renderHome();renderReminders()}}
function renderReminders(){let arr=[...state.reminders].sort((a,b)=>(a.date+"T"+(a.time||"")).localeCompare(b.date+"T"+(b.time||"")));if(reminderFilter==="upcoming")arr=arr.filter(x=>!x.done&&x.date>=isoToday());if(reminderFilter==="done")arr=arr.filter(x=>x.done);const q=($("#reminderSearch")?.value||"").trim().toLowerCase();if(q)arr=arr.filter(x=>x.title.toLowerCase().includes(q));$("#reminderList").innerHTML=arr.map(remCard).join("")||`<div class="empty">لا توجد مواعيد هنا.</div>`}
$$(".filter").forEach(b=>b.onclick=()=>{$$(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");reminderFilter=b.dataset.filter;renderReminders()});$("#reminderSearch").oninput=renderReminders;
function openModal(){$("#modal").classList.remove("hidden");$("#remDate").value=isoToday();$("#remTitle").value="";$("#remTime").value="09:00";$("#remType").value="appointment";$("#remBefore").value="1440";$("#remRepeat").value="none";$("#remRepeatEnd").value=""}
$("#addReminderBtn").onclick=openModal;$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
$("#saveReminder").onclick=()=>{const title=$("#remTitle").value.trim(),date=$("#remDate").value;if(!title||!date)return alert("أدخل عنوان الموعد والتاريخ");const base={title,time:$("#remTime").value,type:$("#remType").value,before:Number($("#remBefore").value),repeat:$("#remRepeat").value,done:false,created:new Date().toISOString()};repeatDates(date,base.repeat,$("#remRepeatEnd").value).forEach((d,i)=>state.reminders.push({id:(crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+i),...base,date:d}));save();$("#modal").classList.add("hidden");renderHome();renderReminders();alert("تم حفظ الموعد"+(base.repeat!=="none"?" مع التكرار":"")+" ✅")};
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();$("#monthTitle").textContent=new Intl.DateTimeFormat("ar-DZ",{month:"long",year:"numeric"}).format(calendarDate);let c=[];for(let i=0;i<first;i++)c.push(`<div class="cal-cell blank"></div>`);for(let d=1;d<=days;d++){const s=`${y}-${pad(m+1)}-${pad(d)}`,has=state.reminders.some(x=>x.date===s&&!x.done),hol=holidays.some(x=>x[0]===s),doc=state.documents.some(x=>x.date===s);c.push(`<button class="cal-cell ${s===isoToday()?"today":""}" onclick="selectDay('${s}')"><span>${d}</span>${has?"<i>•</i>":""}${hol?"<b>★</b>":""}${doc?"<em>▴</em>":""}</button>`)}$("#calendarGrid").innerHTML=c.join("");selectDay(`${y}-${pad(m+1)}-${pad(Math.min(new Date().getDate(),days))}`)}
window.selectDay=s=>{const rs=state.reminders.filter(x=>x.date===s),hs=holidays.filter(x=>x[0]===s),ds=state.documents.filter(x=>x.date===s);$("#selectedDay").innerHTML=`<div class="selected-head"><strong>${fmtDate(s,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</strong></div>${hs.map(h=>`<div class="day-event">🇩🇿 ${h[1]}</div>`).join("")}${ds.map(x=>`<div class="day-event">📄 ${escapeHtml(x.title)} — ${countdown(x.date)}</div>`).join("")}${rs.map(x=>`<div class="day-event">${remIcon(x.type)} ${escapeHtml(x.title)} — ${x.time||""}</div>`).join("")}${!rs.length&&!hs.length&&!ds.length?'<div class="muted">لا توجد أحداث في هذا اليوم.</div>':""}`};
$("#prevMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$("#todayCalendar").onclick=()=>{calendarDate=new Date();renderCalendar()};
function docCard(x){const d=diffDays(x.date);return `<div class="list-item"><div class="item-icon">${x.type==="car"?"🚗":"📄"}</div><div class="item-main"><strong>${escapeHtml(x.title)}</strong><span>${fmtDate(x.date)}${x.note?" • "+escapeHtml(x.note):""}</span></div><div class="item-side ${d<=30?"warning":""}">${d===0?"اليوم":d<0?"منتهية":`باقي ${d} يوم`}<div><button class="mini danger-mini" onclick="deleteDoc('${x.id}')">×</button></div></div></div>`}
function renderDocuments(){let a=dueItems();if(docFilter!=="all")a=a.filter(x=>x.type===docFilter);$("#documentList").innerHTML=a.map(docCard).join("")||`<div class="empty">لا توجد وثائق أو بيانات سيارة.</div>`}
window.deleteDoc=id=>{if(confirm("حذف هذا السجل؟")){state.documents=state.documents.filter(x=>x.id!==id);save();renderDocuments();renderHome()}};
$("#addDocBtn").onclick=()=>{$("#docModal").classList.remove("hidden");$("#docDate").value=isoToday();$("#docTitle").value="";$("#docNote").value=""};$("#closeDocModal").onclick=()=>$("#docModal").classList.add("hidden");
$("#saveDoc").onclick=()=>{const title=$("#docTitle").value.trim(),date=$("#docDate").value;if(!title||!date)return alert("أدخل الاسم وتاريخ الانتهاء");state.documents.push({id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(),title,type:$("#docType").value,date,before:Number($("#docBefore").value),note:$("#docNote").value.trim()});save();$("#docModal").classList.add("hidden");renderDocuments();renderHome();alert("تم حفظ الوثيقة/السيارة ✅")};
$$(".doc-tab").forEach(b=>b.onclick=()=>{$$(".doc-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");docFilter=b.dataset.docfilter;renderDocuments()});
function renderHolidays(){const a=holidays.filter(h=>h[0]>=isoToday()).sort((a,b)=>a[0].localeCompare(b[0]));$("#holidayList").innerHTML=a.map(h=>`<div class="list-item"><div class="item-icon">${h[2]}</div><div class="item-main"><strong>${h[1]}${h[4]?' <span class="tag">تقريبي</span>':''}</strong><span>${fmtDate(h[0])} • ${h[3]}</span></div><div class="item-side">${countdown(h[0])}</div></div>`).join("")}
function loadProfile(){const p=state.profile;$("#userName").value=p.name||"";$("#birthDate").value=p.birthDate||"";$("#workDays").value=p.workDays??20;$("#offDays").value=p.offDays??20;$("#cycleStart").value=p.cycleStart||isoToday();$("#monthlySalary").value=p.monthlySalary||"";$("#payDay").value=p.payDay||30}
$("#saveProfile").onclick=()=>{const p=state.profile;p.name=$("#userName").value.trim();p.birthDate=$("#birthDate").value;p.workDays=Number($("#workDays").value)||0;p.offDays=Number($("#offDays").value)||0;p.cycleStart=$("#cycleStart").value;p.monthlySalary=Number($("#monthlySalary").value)||0;p.payDay=Math.min(31,Math.max(1,Number($("#payDay").value)||30));save();$("#profileSaved").textContent="تم حفظ البيانات ✅";renderHome();setTimeout(()=>$("#profileSaved").textContent="",2500)};
$("#calcSalary").onclick=()=>{const s=Number($("#salaryCalc").value),d=Number($("#salaryDays").value)||30;if(!s||s<0)return;$("#salaryResult").innerHTML=`اليوم الواحد: <strong>${(s/d).toLocaleString("ar-DZ",{maximumFractionDigits:0})} دج</strong><br>الأسبوع تقريبًا: <strong>${(s/4.345).toLocaleString("ar-DZ",{maximumFractionDigits:0})} دج</strong>`};
$("#calcDates").onclick=()=>{const a=$("#dateFrom").value,b=$("#dateTo").value;if(!a||!b)return $("#dateResult").textContent="اختر التاريخين";const diff=Math.abs((new Date(b)-new Date(a))/86400000),m=Math.floor(diff/30),w=Math.floor(diff/7);$("#dateResult").innerHTML=`<strong>${Math.round(diff)} يوم</strong><br>${m} شهر تقريبًا • ${w} أسبوع تقريبًا`};
$("#calcAdd").onclick=()=>{const a=$("#addDate").value,n=Number($("#addDays").value);if(!a||!Number.isFinite(n))return;const s=addDate(a,n);$("#addResult").innerHTML=`<strong>${fmtDate(s,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</strong><br><span class="muted">${s}</span>`};
async function requestNotifications(){if(!("Notification"in window))return alert("هذا المتصفح لا يدعم إشعارات الويب.");const p=await Notification.requestPermission();alert(p==="granted"?"تم تفعيل الإشعارات ✅":"لم يتم السماح بالإشعارات.")}
$("#notifyBtn").onclick=requestNotifications;$("#requestNotify").onclick=requestNotifications;
function checkReminders(){const now=new Date();state.reminders.forEach(r=>{if(r.done||!r.date)return;const target=new Date(`${r.date}T${r.time||"09:00"}`),before=(r.before||0)*60000,key=`notified_${r.id}_${r.date}_${r.before}`;if(!localStorage.getItem(key)&&now>=new Date(target-before)&&now<=new Date(target+60000)){if("Notification"in window&&Notification.permission==="granted")new Notification("مواعيدي 🔔",{body:`${r.title} — ${fmtDate(r.date)} ${r.time||""}`});localStorage.setItem(key,"1")}});state.documents.forEach(x=>{const d=diffDays(x.date),key=`docnotified_${x.id}_${x.date}_${x.before}`;if(d>=0&&d<=Number(x.before||30)&&!localStorage.getItem(key)){if("Notification"in window&&Notification.permission==="granted")new Notification("مواعيدي 📄",{body:`${x.title} — ينتهي ${fmtDate(x.date)}`});localStorage.setItem(key,"1")}})}
$("#exportData").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mawaeedi-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("#importData").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);localStorage.setItem(KEY,JSON.stringify(x));location.reload()}catch{alert("ملف غير صالح")}};r.readAsText(f)};
$("#clearData").onclick=()=>{if(confirm("سيتم حذف كل بيانات التطبيق من هذا الهاتف. هل أنت متأكد؟")){localStorage.removeItem(KEY);localStorage.removeItem(OLDKEY);location.reload()}};
function init(){loadProfile();renderHome();renderHolidays();renderCalendar();renderReminders();renderDocuments();["dateFrom","dateTo","addDate"].forEach(id=>$("#"+id).value=isoToday());setInterval(()=>{renderClock();checkReminders()},1000);checkReminders()}
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));init();
